# Generated by Django 5.1.4 on 2024-12-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.CharField(max_length=255),
        ),
    ]
